### ISSUE TITLE
If git isn't installed, send a message that Git needs to be installed in order to use this version of QPM

### ISSUE THREAD

**Issue by JD-The-65th** [RedBrumbler/QuestPackageManager-Rust#22]
Title says it all.
Old QPM doesn't need git, this one does. When migrating from the versions, some people don't know that git is a requirement, and so the title

**Comment by RedBrumbler** [comment]
Assuming this would just go 

`qpm-rust restore`

->

```
Seems like you do not have git installed! make sure to install it from <insert link here> and then try again!
```

?

**Comment by JD-The-65th** [comment]
Yes, something like that.

**Comment by RedBrumbler** [comment]
Implemented in https://github.com/RedBrumbler/QuestPackageManager-Rust/commit/c5d678dec7f3d8965b550b94f08e106e97df64ae

Still panics but it now tells you to install git
